Keyed node html query fix
eeue56/elm-server-side-renderer pull request #5
Opened 2016-12-01 23:22 UTC by tesk9

Allows for use of the HtmlQuery library when using Html.Keyed.

I considered introducing a new internal type for `KeyedNodeEntry`, but did not do so because I felt unsure about the scope of impact that would have. I'm not sure, for the purposes of this library, whether it's worth making a distinction.

Happy to rewrite this PR/close this PR if that would be your preference.

Should fix test failures on https://github.com/NoRedInk/NoRedInk/pull/14191 (cc @scottcorgan)

2016-12-01 23:51 UTC, eeue56 commented on tests/BasicTests.elm
> +    Keyed.ul [] []
you probably want a test for a keyed node with contents, too

2016-12-01 23:51 UTC, eeue56 commented on tests/BasicTests.elm
> +    Keyed.ul [] []
(and a keyed node in a keyed node)

2016-12-01 23:54 UTC, eeue56 commented on src/ServerSide/InternalTypes.elm
> +                        Json.Decode.map NodeEntry (decodeNode)
this might be wrong - take a look at how decodeTagger is structured.

2016-12-01 23:55 UTC, eeue56 commented
I can't think of a situation where the keyed nodes would have info that isn't obtainable in other ways. We don't really care about the keyed index since we're rendering a given snapshot, and not performing virtual-diffs.

How quickly do you need this merged? I'd like to also merge it to https://github.com/eeue56/elm-html-in-elm

2016-12-02 00:29 UTC, tesk9 commented
👍  I'll address those comments.

How quickly to merge: if I'm guessing, I think by next Wednesday would be good.

Not sure of context on https://github.com/eeue56/elm-html-in-elm -- do you want a kind of analogous PR there, or..?

2016-12-02 02:53 UTC, tesk9 commented on src/ServerSide/InternalTypes.elm
> +                        Json.Decode.map NodeEntry (decodeNode)
Decoding the keyed node children was wrong. Solution I have right now does some processing before stringifying... Not sure how I feel about it. Keeps the decoders tidy, but might be unexpected to have pre-stringing processing?

2016-12-02 03:04 UTC, eeue56 commented on src/Native/ServerSideHelpers.js
> +    }
why do this? the less that can be done in js the better

2016-12-02 04:16 UTC, eeue56 commented on src/Native/ServerSideHelpers.js
> +    }
(decode to a tuple and pull out the second)

2016-12-02 17:56 UTC, tesk9 commented on src/Native/ServerSideHelpers.js
> +    }
Just more convenient for looking at the structure there than in a decoder. Was going to change it after getting the tests...

2016-12-02 18:24 UTC, eeue56 commented on src/Native/ServerSideHelpers.js
> +    }
👍

2016-12-06 16:54 UTC, stoeffel commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
^^ this fixes an issue we ran into with decoders and recursion https://github.com/elm-lang/core/issues/664 it's related to https://github.com/elm-lang/elm-compiler/issues/873

2016-12-06 16:57 UTC, stoeffel commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
this will (should) raise a compiler error in 0.18.

// cc @tesk9

2016-12-06 17:34 UTC, eeue56 commented
what's going on in this PR atm?

2016-12-06 17:47 UTC, stoeffel commented
I helped @tesk9 to fix an issue with the tests. I think it should be ready
for a review

On Tue, Dec 6, 2016, 18:35 Noah <notifications@github.com> wrote:

> what's going on in this PR atm?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/eeue56/elm-server-side-renderer/pull/5#issuecomment-265216385>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABKUkdDFK27Ski1tPZER9c__L7KVtkWxks5rFZzDgaJpZM4LCA3C>
> .
>

2016-12-06 19:31 UTC, tesk9 commented
Not to be overly specific, but this was failing:
```
...

   ("children" := Json.Decode.list decodeKeyedNodeType)
...

decodeKeyedNodeType : Json.Decode.Decoder NodeType
decodeKeyedNodeType =
    Json.Decode.at [ "_1" ] decodeNodeType
```

And this fixed it:

```
   ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
```

Was so confused at why things weren't working... @stoeffel is 🏆

2016-12-06 23:02 UTC, eeue56 commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
Please pull `Json.Decode.at [ "_1" ] decodeNodeType` out into it's own decoder with a name that explains what you're pulling out and wherefrom (e.g, why don't we care about the other fields in this object?)

2016-12-06 23:02 UTC, eeue56 commented on tests/BasicTests.elm
> -    --[]
Please leave this back in - it explains what the next few lines do.

2016-12-06 23:05 UTC, eeue56 commented on tests/BasicTests.elm
> +keyedNodeWithChildrenDecoded childrenCount =
`keyedNodeWithChildrenDecoder 2` does not make clear sense of what the function is doing. Please give a comment explaining

2016-12-06 23:06 UTC, eeue56 commented on tests/BasicTests.elm
> +keyedNodeWithChildren : Int -> Html.Html msg
please move the helper functions either to another field or to the bottom of this one. The progression should be:

- base case triplets, where there's the string version, the Html version, and the decoded version
- the tests themselves, where it shows how each of these connect

- <rest>

2016-12-06 23:06 UTC, eeue56 requested changes
🎨 things that I'd like addressed before merging, but otherwise looks good, thanks!

2016-12-07 01:21 UTC, tesk9 commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
@eeue56  funny thing! can't do it. this is the recursion bug thing I was talking about: https://github.com/eeue56/elm-server-side-renderer/pull/5#issuecomment-265248450

2016-12-07 01:22 UTC, tesk9 commented on tests/BasicTests.elm
> -    --[]
Oh-- looked like a mistake because of the comment style.

2016-12-07 01:38 UTC, eeue56 commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
You can move it to a let binding and it'll work

2016-12-07 01:40 UTC, eeue56 commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
e.g

```
decodeKeyedNode :  Json.Decode.Decoder NodeRecord
decodeKeyedNode =
    let
        -- elm stores keyed nodes as tuples
        -- we only want to decode the html, in the second property
        decodeSecondNode = (Json.Decode.at [ "_1" ] decodeNodeType)
    in
        Json.Decode.object4 NodeRecord
            ("tag" := Json.Decode.string)
            ("children" := Json.Decode.list decodeSecondNode)
            ("facts" := decodeFacts)
            ("descendantsCount" := Json.Decode.int)
```

2016-12-07 01:53 UTC, eeue56 commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
You can also do this:


```elm
decodeKeyedChildren value =
    let
        -- elm stores keyed nodes as tuples
        -- we only want to decode the html, in the second property
        decodeSecondNode = (Json.Decode.at [ "_1" ] decodeNodeType)
    in
        Json.Decode.decodeValue (Json.Decode.list decodeSecondNode) value
            |> (\result ->
                case result of
                    Ok children -> Json.Decode.succeed children
                    Err message -> Json.Decode.fail message
                )

decodeKeyedNode :  Json.Decode.Decoder NodeRecord
decodeKeyedNode =
    Json.Decode.object4 NodeRecord
        ("tag" := Json.Decode.string)
        ("children" :=
            Json.Decode.value
                |> (flip Json.Decode.andThen) (\value -> decodeKeyedChildren value))
        ("facts" := decodeFacts)
        ("descendantsCount" := Json.Decode.int)
```

2016-12-07 01:54 UTC, eeue56 commented on src/ServerSide/InternalTypes.elm
> +        ("children" := Json.Decode.list (Json.Decode.at [ "_1" ] decodeNodeType))
or just use customDecoder, but that's gone in 0.18

2016-12-07 09:57 UTC, stoeffel commented on tests/BasicTests.elm
> +-- creates a keyed `ul` with `n` children (`li`).
I added comments to the helpers for clarification

2016-12-07 09:57 UTC, stoeffel commented on tests/BasicTests.elm
> +keyedNodeTwoKeyedChildren =
added aliases to make the tests easier to read. let me know if you think it's overkill.

2016-12-07 09:59 UTC, stoeffel commented
@eeue56 I addressed your comment. Let me know if you want me to change more things. @tesk9 I hope you don't mind that I addressed the comments, I thought it's better to have this in soon.

2016-12-07 22:04 UTC, eeue56 commented
reasonable, thanks!

2016-12-07 22:04 UTC, merged